### ISSUE TITLE
Do you any csv with the translation?

### ISSUE THREAD

**Issue by Matthew32** [dackst/nayuta#17]
Hi,

sorry for interrupt you,

i want to make a lite application for the playstation 4 version, (somewhat like the one zerofield did for hajimari), just to know, if you still have some kind of file with the text of the game.

thank you in advance.

**Comment by dackst** [comment]
If you run `spread.py` from within the script folder (after dumping the Japanese script with `scriptdump.py`), you should get a tsv formatted similar to the zerofield one (a name, an English line, and a Japanese line in each row).

From there you'd probably want to work on actually putting the lines in chronological order.

**Comment by Matthew32** [comment]
ok, thank you!
