### ISSUE TITLE
Various spelling and grammar issues for items and descriptions

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#2]
First off, great job so far with polishing up the English patch.
This is just a list of incorrect spelling and grammar I found when going through ingredients, equipment, achievements, food, and enemy info.

![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/98383764-e64d5b80-201a-11eb-8127-8c6564254173.jpg)
the word "where" doesn't work here. I think either removing it or changing it to "well" would flow better.

![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/98383965-29a7ca00-201b-11eb-9e93-7eb9f605b032.jpg)
I personally feel there should be a period after the word "injuries", as the way it is now could be misinterpreted to be about a group of mountain climbers that weaponized injuries.

![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/98384558-e7cb5380-201b-11eb-8f17-37503a56c23b.jpg)
I've always felt this description was a little clunky. Maybe have the second sentence be "Makes your body feel like it can float." would work better?

![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/98384975-72ac4e00-201c-11eb-8fd1-9438247fdaab.jpg)
Nothing exactly wrong with this description, except for the fact that the achievement also requires all equipment in addition to weapons.

![NPJH50625_00005](https://user-images.githubusercontent.com/73907314/98385265-c9b22300-201c-11eb-8cb7-510b61e9e4ea.jpg)
"Especially" is misspelled as "Expecially".

![NPJH50625_00006](https://user-images.githubusercontent.com/73907314/98385434-f9f9c180-201c-11eb-9549-b416282baae7.jpg)
So I noticed you changed the name for one of the foods called "Fish Fry" so they would be unique. Since there is another food called "Meat Bun", this one might be better being called "Steak Bun" based on its description.

Last note about foods, I noticed you changed the food "Box Lunch" to "Boxed Lunch". This is slightly inconsistent with the recipes "Quality Tartare", "Solid Liver Lunch", "Jungle Rice", "Royal Paella", "Fermented Meat", "Noble Rib Box Lunch", and "Gorgeous Box Lunch", which either use the term box lunch in their name or description. Not entirely sure it this was intentional.
This is also the case with the event item gotten during the prologue called "Eartha's Box Lunch".

![NPJH50625_00016](https://user-images.githubusercontent.com/73907314/98386316-0599b800-201e-11eb-9e5c-aa4da14a9001.jpg)
From what I can find, "threaning" is not a word. Was this supposed to be "threatening", or something else?

![NPJH50625_00017](https://user-images.githubusercontent.com/73907314/98386474-37128380-201e-11eb-9bbf-efb8af4deaf5.jpg)
"it" should be "its".

![NPJH50625_00018](https://user-images.githubusercontent.com/73907314/98386556-55787f00-201e-11eb-9e29-02a6f8bb1ec1.jpg)
Not sure if this one can be changed or not, but the text in the sub-menu during chapter 5 refers to Creha with the original translation name of Kureha.

And that's all I could find at this time. Apologies for the length of this post.

**Comment by dackst** [comment]
Yeah, I admit I didn't pay as much attention to changing the item and monster descriptions as I did for other things like the script, and some of these were introduced from what I did change. 

I ran into the same thing with the sub-menu text. It only occurs if you load a save from the original translation (or from the unmodified game in Japanese). If you continue to the next objective, it should use the correct text. It appears that the current objective is loaded directly from your save file.

Everything you else mentioned here should be fixed with my next commit.

**Comment by Wandering-Heiho** [comment]
Good to know about the sub-menu text when loading a save file from the original translation, I probably should've tested getting to that point instead of using an old save file.

One more thing I forgot, although one of the sword arts' name was changed to Whirlwind (the upgraded Kamaitachi), the image for when you unlock it still refers to it as Divine Wind.
![h_050_02](https://user-images.githubusercontent.com/73907314/98424791-e112ff80-2060-11eb-8fa1-3efa35097b50.jpg)
This image's location is visual -> help and file name is h_050_02.itp
Thankfully, there is a version of the image with no text on the right side, so keeping the background texture should not be as difficult to do (the file is in the same place and is called h_050_01.itp).

**Comment by dackst** [comment]
I don't think I change any of the skill names. In this case it would be easier to just change "Whirlwind" to "Divine Wind".

**Comment by Wandering-Heiho** [comment]
Yeah, that makes sense.
