### ISSUE TITLE
stamps/seals and sword techs/sword arts and sidequest description

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#3]
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/98501498-6511e680-221d-11eb-9406-e5bdece8beb9.jpg)
When Cygna gives the Training Book to Nayuta in chapter 1, he refers to filling it up with stamps, but both the notification for collecting enough and the in-game manual images refer to them as seals (from checking the file mp_0002.tsv in script/input, it seems Orvus also makes this mistake).
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/98501515-722ed580-221d-11eb-8a05-833c0af1bf14.jpg)
In addition to the stamps/seals, the notification message when you get enough seals uses the term "sword tech", yet the images in the in-game manual uses "sword art".
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/98501528-7bb83d80-221d-11eb-82bd-b248bcf47da9.jpg)

Final note on this subject, would it be possible to change the description for achievement "Secret Sword Dancer" to call them "sword arts" instead of "sword skills"?
![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/98501543-84107880-221d-11eb-9c0f-4680f9581d69.jpg)

![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/98511832-5c2c0f80-2233-11eb-8bd4-34363a2e05d1.jpg)
Another thing I noticed was the grammar of the Work Repair sidequest description. "broken" I believe should either be changed to "broke" or "is broken".

**Comment by dackst** [comment]
For the swords, I'd rather not call them "[arts](https://kiseki.fandom.com/wiki/Orbal_art)" since that's typically reserved for magic in other kiseki games. Even in this game, with no mention of orbments, they still use arts/アーツ/aatsu to refer to magic. What they call the sword stuff is 剣技 (kengi). I'll rather change it to "technique" or "skill," but editing manual graphics will be a pain.

The other stuff should be fixed though.

**Comment by Wandering-Heiho** [comment]
Speaking of editing graphics, what is your opinion of editing the Chapter 5 image from this:
![p_st5](https://user-images.githubusercontent.com/73907314/98705585-e10a4c80-234b-11eb-963c-4e635753c38e.png)
to this?
![p_st5](https://user-images.githubusercontent.com/73907314/98705619-e7002d80-234b-11eb-9c70-78447cc596ca.png)

Text was based on the Chapter 5 End image, but with Mythos changed to Mitos.

**Comment by dackst** [comment]
Hey, that looks nice. How did you edit the text, like the font and stuff? What I did with the status condition graphic was Frankensteining letters from other text, but the background was much simpler, with no stars. I've been looking at doing the same for the "sword art" text, but there are some missing letters, and the yellow headers seem to use the same serif font.

For the Chapter 5 titles, I sort of rationalized that "mythos" is a real word, and at the end of it they did find out that humanity's mythos about there once being a great flood and living with gods and all that is all true. It was slightly more bothered that the title changed between the start and end of Chapter 5. 

If you'd be willing to do the other graphic for the end of Chapter 5, I can certainly add them in.

**Comment by Wandering-Heiho** [comment]
Making sure the background was accurate was probably the hardest part. I took all of the chapter start images (both the Japanese and the original English patch version) and tried to find the small sections not covered up by text to then merge them together. There were a couple small spots that were always too close to text, so I had to use other parts of the image to make it look as close as possible.

For the font, I took the image and used it on some sites that would try and identify it. From there, it was basically just trial and error of matching the size, character spacing. and effects like a drop shadow. By doing this, editing the text can be done quickly without changes in the quality.

Good news about the Chapter 5, I also did the same thing for that one.
![p_ed5](https://user-images.githubusercontent.com/73907314/98852662-0075a800-2426-11eb-971f-9f889d9e13fb.png)

On the subject of the images in the manual, I also spent some time working on those. While not finished yet, I have completed a cleaned background, figured out the font and effects to the text at the top, and recreated the text talking about getting rewards for getting 6 seals.

![h_030_01](https://user-images.githubusercontent.com/73907314/98853167-bb9e4100-2426-11eb-9be4-9161e54ffc7f.png)
![h_200_01](https://user-images.githubusercontent.com/73907314/98853181-be993180-2426-11eb-9e10-f3baaca08e4c.png)
Couple questions before I edit images like the Down Thrust:
1) Do we want to refer to them as sword skills, sword techs, or sword techniques? Based on how I have the files prepared, this can be a quick and easy change.
2) What file format would you like the images in? Does having them like png's work, or would you prefer something else?

**Comment by dackst** [comment]
"Sword techniques" is what I was planning to go with. Although the manual menu says "Swdtech:Whatever" and the text in `helplib` is one of the things that I'm currently not able to successfully change, "tech" can be probably understood to be an abbreviation of technique, like "Swd" is an abbreviation of "sword". (I *was* going to change it to "Sword/Whatever" to match the other "Mastery/Whatever" stuff you receive from Orvus.)

How you posted them here works:
![NPJH50625_00032](https://user-images.githubusercontent.com/35816592/98877904-97a32580-244f-11eb-9b00-f4ac0d11f43f.png)
(Well, for clarity's sake, the ITP converter seems to only take images with an 8-bit color depth, so I had to convert them first for that to work. And bizarrely, they then show up as completely [transparent](https://user-images.githubusercontent.com/35816592/98878167-53645500-2450-11eb-85ba-77341b5a6ac5.png), but editing the dumped images by just copying your changes on top of them worked for me to make them show up correctly.)

Since it seems like you redid all the purple text in the [stage results](https://user-images.githubusercontent.com/35816592/98878220-742caa80-2450-11eb-889f-28cea807987f.png), could you also capitalize "master"? Or maybe "your master", whichever you think sounds better.

**Comment by Wandering-Heiho** [comment]
Using "Sword / Name" at the top does make the most sense for consistency, especially since we have the term "Sword Technique" right below it.

Interesting how they appeared transparent unless the changes are copied over to the original images (I really have no idea why that happens). I was a little worried when I tried turning them into 8-bit color depth bmp's before using the ITP converter and got that exact same result, good to know you found a work around.

I'll make sure to do the capitalization change for "master".

**Comment by Wandering-Heiho** [comment]
And all of the image edits are done. There were a couple more I did small changes to, like Basic Controls 2 to change "sub-menu" to "submenu". A small txt file is included listing all of the changes done. It there's any alterations to these you want done, just let me know.
[Nayuta_no_Kiseki_-_Manual_Image_Edits.zip](https://github.com/dackst/nayuta/files/5531788/Nayuta_no_Kiseki_-_Manual_Image_Edits.zip)

**Comment by dackst** [comment]
A couple things in your changes I was able to fix:
* misspelled "Swallow" as "Swalow"
* lost a period in the basic control page where there was one before
* changes to `h_010_1` should also be applied to `h_010_2`
* there was some stray black pixels in some of the sword techniques, and too much space after the m in "mira"

I also ignored the double jump part. [Double jump](https://en.wikipedia.org/wiki/Glossary_of_video_game_terms#double_jump) probably shouldn't be hyphenated in the first place (see also: literally every other example on google), so I changed the few times it appeared in the text. I also noticed you moved "Secret Technique" one pixel up, so it's vertically aligned with "Sword Technique". I made sure to copy all of those over, even when the original already said "Secret Technique"

More changes I made:
* magics -> arts
* if you're going to lowercase the "each" in stage results, might as well lowercase "stage" as well
* removed "the" from "the treasure chest", as some levels have multiple chests
* some black descriptions of sword techniques ended with a period, some didn't. they should all have periods at the end now.
* moved "sword techniques" and "secret technique" titles to be same position on every sword page

**Comment by Wandering-Heiho** [comment]
Thanks for catching all of those, apologies for missing them and/or causing them.
