### ISSUE TITLE
Some More Spelling Errors Found

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#4]
Starting off simple, the word "one" is repeated back-to-back in the first conversation with Cetus and Reticul in New Game+.
![mp_2002b tsv line 123   124](https://user-images.githubusercontent.com/73907314/99322745-9e121280-283e-11eb-8561-dbb3f042f548.jpg)
Looking through the files on here, I _think_ this is located in mp_2002b.tsv at lines 123 and 124.

Speaking of New Game+, do we want to change the description for "Four Season Magic" from:
"Keep learned magic, magic levels, and slots."
to
"Keep learned arts, art levels, and slots."

Lastly, I looked through the updated Enemy Info. Here's the things I noticed.
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/99323813-f64a1400-2840-11eb-8943-56580b495397.jpg)
For this one, was "Uses it speak-like beak" supposed to be "Uses its spear-like beak"?

There is only one enemy I could find with a different name when defeated compared to the one in Enemy Info, it's the last of the four enemies you defeat to get Zemurian Ore.
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/99324187-b46d9d80-2841-11eb-81d4-e87ff800dee4.jpg)
When defeated, it's called "Yak Tool", but Enemy Info calls it the "Yakuto Douga".
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/99324226-cc452180-2841-11eb-92be-c90371e4305a.jpg)

**Comment by dackst** [comment]
I changed the monster to "Yak Drudger". It's literally "Yakuto Douga" in Japanese, and I remember not being sure what it should be.

> "Keep learned magic, magic levels, and slots."
> to
> "Keep learned arts, art levels, and slots."

I'm not sure about this one either. In my mind arts are like a subset of magic, so either would work, but I might be wrong. I changed the the previous manual graphic because I thought "arts" was less awkward than "magics" (plural).

I fixed the other typos.

**Comment by Wandering-Heiho** [comment]
Congratulations on solving the talking to Mishy and Volan's Japanese text problems.

I came across another textbox that had a word repeated, this time it was "teleporter". Funny enough, it was in another conversation with Cetus and Reticul.
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/99825275-d2c6e800-2b24-11eb-8f24-96df333ee5ec.jpg)
From searching the files, I think this is in text/input/mp_1100.tsv, at lines 115 and 116.

Aside from that, I believe I some arts that have a different name when you obtain them, compared to their name in the equip menu.
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/99825940-b2e3f400-2b25-11eb-89d7-722b3dc1f17b.jpg)
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/99825949-b4152100-2b25-11eb-9f7f-46abfab76b1a.jpg)

The art gotten from defeating Vulkanon
Obtained text (script/input/mp_2000c.tsv at line 21) Speed Fire
Inventory text (text/input/item.tsv at line 487) Spitfire

The art gotten from defeating Noire Palace
Obtained text (script/input/mp_2001a.tsv at line 34) Noire Haze
Inventory text (text/input/item.tsv at line 497) Noir Haze

The art gotten from defeating Tempano
Obtained text (script/input/mp_2002d.tsv at line 15) Frost Web
Inventory text (text/input/item.tsv at line 465) Frost Wave

The art gotten from defeating Evil Typhon
Obtained text (script/input/mp_7020.tsv at line 22) Hailstorm
Inventory text (text/input/item.tsv at line 495) Hell Storm

____________________________________
Lastly, this isn't an issue with the game or the patch, but more so something I started working on. I did some research into extracting and creating the pmf videos, as I wanted to try changing the opening movie's Japanese text. And yes, I've successfully been able to replace the files.
The only part of the opening I've edited so far is the text at the very end.
![End_Section_Edited](https://user-images.githubusercontent.com/73907314/99826689-b5931900-2b26-11eb-869f-02a9713b7cf5.gif)
I can't promise if/when I'll finish it, as editing the part with the logo will probably take a while, but if I do, would you be interested in adding it in?

**Comment by dackst** [comment]
Thanks for that. I completely forgot that spell names I changed recently also appear in the script. 

Besides the opening logo and the credits, I can't recall there being very much text in the movies. But if you do end up making a finished version that works, I'd be willing to include them.
