### ISSUE TITLE
Dialogue Errors Found During Chapter 4

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#5]
Just finished going through Chapter 4 of a New Game+ run I was doing, hence why I'm starting a full chapter analysis here instead of the Prologue.

To start, I found a third instance of a word being repeated (although this is also technically the fourth, as there are two sets of dialogue with this error).
![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/101234191-4d4a4880-368b-11eb-816f-a00f2d0daf89.jpg)
From looking through the script files here, this is at lines 89-90, and 97-98 in script/input/mp_0002.tsv
__________
Prof. Volans seems to be mistaken with his words by using "Tough" instead of "Though".
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/101234266-b467fd00-368b-11eb-9653-64116b684fd8.jpg)
Found at line 162 in script/input/mp_0115.tsv
__________
Algol seems to have made a blunder at the end of his motivational speech after his sidequest by saying "You must ever give up." instead of "You must never give up."
![NPJH50625_00010](https://user-images.githubusercontent.com/73907314/101234316-23455600-368c-11eb-8a8b-5c26923ae619.jpg)
Error happens twice in the script file, at lines 45 and 311 in script/input/mp_3099.tsv
__________
This next one could just be me, but I feel having "...Hurry up!" followed by "C'mon" just seems a little clunky. One suggestion would be to change it to:
"...Hurry up!
We gotta quickly get
the Master Gear back!"
![NPJH50625_00007](https://user-images.githubusercontent.com/73907314/101234335-55ef4e80-368c-11eb-968c-e5864ed8e181.jpg)
This dialogue was found at lines 54-56 in script/input/mp_4011.tsv
__________
A couple small things when talking with Boote. This first one I feel would flow better if the first line was changed to "I was just collecting star".
![NPJH50625_00005](https://user-images.githubusercontent.com/73907314/101234474-98655b00-368d-11eb-9083-1f8f0ee212ef.jpg)
It was located at line 245 in script/input/mp_0114.tsv
________
Just to make sure, should the "I" in "it." be capitalized or not?
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/101234451-5c31fa80-368d-11eb-9675-6a6648529665.jpg)
This is located at line 266 in the same file as the last one, script/input/mp_0114.tsv
________
This next one is mainly me wanting to make sure if this was just a coincidence or purposefully done. During the Employer Arbitration sidequest, Nayuta always refers to Sasha's Grandmother as "Ms. Camelope", but the text in the side quest menu and text boxes stating events always refers to her as "Mrs. Camelope" or "Camelope". Is this how it should be?
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/101234565-8f28be00-368e-11eb-8a6c-4baa6d1ed6ab.jpg)
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/101234568-8fc15480-368e-11eb-8a6f-8d1e548427fc.jpg)
_________
This one isn't about the dialogue specifically, but it's about the text box. For some reason, two small boxes appear to the right of this dialogue box for some reason.
![NPJH50625_00011](https://user-images.githubusercontent.com/73907314/101234594-bf705c80-368e-11eb-837b-098794bf1673.jpg)
After checking Flame's version 4.15 translation, which didn't have this problem, my guess is that it's somehow related to the text box length.
![NPJH50625_00012](https://user-images.githubusercontent.com/73907314/101234598-ca2af180-368e-11eb-9b98-14d1bbb4fcdd.jpg)
This was at line 305 in script/input/mp_0002d.tsv
_________
Alright, this last one is not from Chapter 4 specifically, but it's about four stage names that all have a slight discrepancy between their world map name and their name stated when you enter the stage and in the submenu. The final stages on the four continents are called "Temple/Inner Sanctum" on the world map, but is called "[Continent Name] Temple/Sanctum" inside the stage.
![NPJH50625_00008](https://user-images.githubusercontent.com/73907314/101234654-36a5f080-368f-11eb-8959-e8433c2cd4dc.jpg)
![NPJH50625_00009](https://user-images.githubusercontent.com/73907314/101234655-37d71d80-368f-11eb-8868-e489335968f6.jpg)
Wasn't entirely sure if this was done due to stage name length, so I figured I would bring it up.

And that was everything I noticed in Chapter 4.

**Comment by dackst** [comment]
The text box thing is interesting. I'm thinking it's a combination of the text box size and the positional arguments (#500x#100y) leading to the game trying to draw the box off-screen. I've never really messed with them, but like, if the x position uses the right edge of the box, a smaller sized box could marked to be completely off-screen (And I guess the previous position would have had to been fine being only partially off-screen). Changing it to what I believe should indicate a more leftward position seems to fix it.

![NPJH50625_00089](https://user-images.githubusercontent.com/35816592/101244338-e69d4d00-36d3-11eb-911e-03118378458c.jpg)

---

There's this weird thing that exists both in the previous translation and in the original Japanese that the text boxes *only* use honorifics (no -sans or -kuns or anything like that) for job titles like Captain or Elder, and for older, presumably married women. Mensa is Mensa-fujin, Camelope is Camelope-fujin, Janis is Janis-obasan, and all which was turned into a "Mrs." in the original translation. (Canie and Carina don't get one for some reason, and there are no ojisans, despite Nayuta using that for some of the male adults.)

My thinking was that Camelope seems to be her family name, so I would keep the Mrs. to some degree, but Nayuta has no reason to be aware of her marital status. But I guess being the matriarch of some high society family with kids and a granddaughter is reason enough to assume she was married at some point. I'll just give her a "Mrs." everywhere (and give Barton, another character known only by surname, a "Mr." while I'm at it).

The Temple vs. [Continent] Temple thing was also done in Japanese, even though I'd probably assume they have enough space on the world map. Either way, there's clearly not enough space in English. There *is* space to expand "Sanctum" to "Inner Sanctum" while inside though.
