### ISSUE TITLE
Dialogue Errors Found During Chapters 5, 6, and 7

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#7]
Decided to include all three of these chapters as there weren't too many errors found in a single one.
### Chapter 5
I believe the contraction Nayuta is supposed to say is we've (we have) and not we're (we are).
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/104145960-042a9a00-5397-11eb-88c2-95247fd0c010.jpg)
I believe this is at line 200 in script/input/mp_5098.tsv
________
### Chapter 6
Small change here, pretty sure there should be an "and" after Creha.
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/104146090-769b7a00-5397-11eb-9483-555c5240cdba.jpg)
Found at line 65 in script/input/mp_0112.tsv
___
Pretty sure Dorado meant to say "can" and not "can't" here.
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/104146183-d42fc680-5397-11eb-94ad-2f03a1845185.jpg)
Located at line 19 in script/input/mp_0001c.tsv
___
### Chapter 7
Pretty sure this is supposed to be "With that," and not "What that,".
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/104146256-19ec8f00-5398-11eb-876f-8ac9449b9a4b.jpg)
I believe this is line 53 in script/input/7098.tsv
___
Grammatically, this should either be:
"Yeah... Thanks to your guy's little intervention." 
or
"Yeah... Thanks to you guys intervening."
![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/104146288-37215d80-5398-11eb-96db-81e75d3adde4.jpg)
Found at line 91 in script/input/7098.tsv
___
I believe there should be a "to" before "lose".
![NPJH50625_00005](https://user-images.githubusercontent.com/73907314/104146293-3ab4e480-5398-11eb-9f77-8911719496ae.jpg)
At line 412 in script/input/7098.tsv
___
### _MISC_
Something small about the Ruins Rock Salt description. All my searching seems to show that there are 2 c's in occurring, while this description only has 1.
![NPJH50625_00006](https://user-images.githubusercontent.com/73907314/104146374-7bacf900-5398-11eb-82ba-e96ad88d4c76.jpg)
line 716 in text/input/item.tsv
___
That's all I have for now.

**Comment by dackst** [comment]
> I believe the contraction Nayuta is supposed to say is we've (we have) and not we're (we are).

I don't think it's [completely wrong](https://www.youtube.com/watch?v=nPlbOv4wUoI), but other examples I can find of it being used off Google *are* a little strange. It should be "If that's decided" now.

> Pretty sure Dorado meant to say "can" and not "can't" here.

I did this as an attempt of expressing uncertainty, like "Isn't there anything we can do?" Expressing uncertainty was my interpretation of machine translators throwing around "somehow" all over the place. There's probably better ways of expressing that than what's there currently, though.

> Grammatically, this should either be:
> "Yeah... Thanks to your guy's little intervention."
> or
> "Yeah... Thanks to you guys intervening."

I'm not so sure, this seems to be a point of contention, with no single agreed upon answer.
https://www.thecut.com/2016/11/your-guys-is-american-english-at-it-roughspun-best.html
https://english.stackexchange.com/questions/12277/what-is-the-possessive-of-you-guys
https://en.wiktionary.org/wiki/you_guys

If we search the scripts of other Trails games, *your guys'* is used a [bunch of times](https://trailsinthedatabase.com/game-scripts?p=1&q=your%20guys%27%20&strict_search=1) (but interestingly not once in the Sky games), *you guys'* is used [once](https://trailsinthedatabase.com/game-scripts?p=1&q=you%20guys%27%20&strict_search=1), and *your guy's* is [never used](https://trailsinthedatabase.com/game-scripts?p=1&q=your%20guy%27s&strict_search=1).

While I think Cygna's dialogue especially could stand to be spiced up with some slang, it might flow a little better in this case to get rid of the *guys* altogether.

**Comment by Wandering-Heiho** [comment]
> I'm not so sure, this seems to be a point of contention, with no single agreed upon answer.
> https://www.thecut.com/2016/11/your-guys-is-american-english-at-it-roughspun-best.html
> https://english.stackexchange.com/questions/12277/what-is-the-possessive-of-you-guys
> https://en.wiktionary.org/wiki/you_guys
> 
> If we search the scripts of other Trails games, _your guys'_ is used a [bunch of times](https://trailsinthedatabase.com/game-scripts?p=1&q=your%20guys%27%20&strict_search=1) (but interestingly not once in the Sky games), _you guys'_ is used [once](https://trailsinthedatabase.com/game-scripts?p=1&q=you%20guys%27%20&strict_search=1), and _your guy's_ is [never used](https://trailsinthedatabase.com/game-scripts?p=1&q=your%20guy%27s&strict_search=1).

Yeah, that was my mistake, I meant to type your guys' but misplaced the apostrophe. Sorry about that.
