### ISSUE TITLE
 Dialogue Errors Found During After Story and Prologue

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#8]
### After Story
I think based on his dialogue before and after this, Ax means to use "your" instead of "our".
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/106157652-ec9e3000-6150-11eb-84ac-10c522b18c11.jpg)
line 195 in script/input/mp_0117.tsv
___________
Considering that Lupus brings up that Noi has lost her memory immediately after this, I believe he is supposed to be referring to the Sea Ruins, as that's where Noi landed this time (or it could be changed to just "ruins", as there are multiple in the sea).
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/106158266-8fef4500-6151-11eb-8594-c59da80ebb23.jpg)
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/106158271-91207200-6151-11eb-9366-c06d3dec1b7c.jpg)
line 205 in script/input/mp_0000.tsv
___________
Just a small inconsistency with a quest name. Started and completed text call it "Offering for Ancestors", but the mailbox and quest menu calls it "Ancestral Offering".
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/106158412-b4e3b800-6151-11eb-9520-2971f035dd43.jpg)
![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/106158419-b6ad7b80-6151-11eb-941c-8010ad9d4d88.jpg)
___________
Despite giving Cygna the title at earlier points in this conversation, Noi does not refer to him as "Lord Cygna" here.
![NPJH50625_00006](https://user-images.githubusercontent.com/73907314/106158726-0b50f680-6152-11eb-9591-6c15ff1f8945.jpg)
line 77 in script/input/mp_8100b.tsv
___________
### Prologue
I think this would flow better if "much" was changed to "many".
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/106158868-34718700-6152-11eb-94f2-abb9534646ac.jpg)
line 212 in script/input/mp_0001.tsv
___________
I think Nayuta meant to say "Hey, girl, wanna come over to my house?".
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/106158930-40f5df80-6152-11eb-862e-04a87ee017c6.jpg)
line 176 in script/input/mp_0001.tsv
___________
Fairly certain that "should" and "we" are supposed to be in the opposite order here.
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/106158968-4c490b00-6152-11eb-9ec8-07654c6f759d.jpg)
line 93 in script/input/mp_0004.tsv
___________
I believe there should be an "is" after "This".
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/106158994-54a14600-6152-11eb-9144-9e4a88812562.jpg)
line 476 in script/input/mp_0004.tsv
___________
"to" doesn't really work in this statement followed by "gotta" in my opinion.
![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/106159028-5f5bdb00-6152-11eb-8fd7-957fca5a7782.jpg)
line 349 in script/input/mp_0003.tsv

**Comment by dackst** [comment]
> (or it could be changed to just "ruins", as there are multiple in the sea).

The Japanese line is "突如光とともに遺跡に降ってきた妖精ノイ。", which as far as I can determine, doesn't specify either the Sea Ruins (海上の遺跡) or the tower (遺跡塔). The tower thing was carried over from the original translation, which for some reason specified "ruined tower". So you're right, and it should be just ruins.

> Just a small inconsistency with a quest name. Started and completed text call it "Offering for Ancestors", but the mailbox and quest menu calls it "Ancestral Offering".

I was sure that I went and made them all consistent, but I guess I must have shortened "Offering for Ancestors" to prevent text overlapping in the mailbox at some point after that.

> Despite giving Cygna the title at earlier points in this conversation, Noi does not refer to him as "Lord Cygna" here.

This particular line in Japanese starts with "Kureha-sama to Siguna" (クレハ様とシグナ……). I rechecked the scenes immediately before this where she uses "Lord Cygna", and in Japanese, they mostly appear as "Kureha-sama-tachi". I don't want to say "Lady Creha and the others" here when there's only one other, everyone knows who it is, and one doesn't seem to take much priority over the others (I can remember a lot of Zext-tachis before Selam's name is revealed that were shortened to either Zext or just "them"). She uses "Siguna-sama" (とシグナ様) in other lines.

But then I noticed that "Siguna-sama" is only used when she doesn't have her memories, so maybe it's supposed to indicate she doesn't personally know Cygna, and then she drops the "sama" after regaining them? Not something that I realized before. Anyway, I'll get rid of every other "Lord Cygna" after she regains her memories instead.

> I think this would flow better if "much" was changed to "many".

This was something I couldn't figure out which was correct, and everything I could find that said "much people" is absolutely bad weren't using it in the same way in their examples. But might as well change it to "many" anyway, I haven't seen anything that says "many people" is bad.
