### ISSUE TITLE
Do I have to convert the Patched file to .ISO?

### ISSUE THREAD

**Issue by 4GAP3** [dackst/nayuta#9]
I tried to played the patched ISO with my emulator but I can't because it's not an .ISO

Do I need to convert the file to an ISO in order to play it or is there a step that i'm missing

**Comment by dackst** [comment]
Does the patched file's name end in ".iso"? Try renaming so it does if it doesn't already.

**Comment by 4GAP3** [comment]
It works now, thank you.
